# ==============================================================================
# Configuration du module bootloader pour Arrera Linux
# Par défaut : GRUB2 + Shim (Secure Boot certifié Microsoft pour x86_64)
# Note : Sur aarch64, le kickstart applique la configuration systemd-boot.
# ==============================================================================
---
efiBootLoader: "sb-shim"

kernelSearchPath: "/usr/lib/modules"
kernelPattern: "^vmlinuz.*"

loaderEntries:
  - "timeout 0"

kernelParams: [ "rhgb", "quiet", "splash", "loglevel=3", "rd.udev.log_priority=3", "systemd.show_status=false", "vt.global_cursor_default=0" ]

bootloaderEntryName: "Arrera Blue 2026"

grubInstall: "grub2-install"
grubMkconfig: "grub2-mkconfig"
grubCfg: "/boot/grub2/grub.cfg"
grubProbe: "grub2-probe"
efiBootMgr: "efibootmgr"

efiBootloaderId: "fedora"
installEFIFallback: true
