# ==============================================================================
# Configuration du module partition pour Arrera Linux
# Par défaut : ESP sur /boot/efi (Standard Fedora pour GRUB2 sous x86_64)
# Note : Sur aarch64, le kickstart configure l'ESP sur /boot (1024M) pour systemd-boot.
# ==============================================================================
---
defaultFileSystemType:  "ext4"

availableFileSystemTypes:  ["ext4", "btrfs", "xfs"]

createHybridBootloaderLayout: false

defaultPartitionTableType: "gpt"

# Point de montage de l'ESP pour GRUB2 sous Fedora : /boot/efi
efiSystemPartition: "/boot/efi"

# Taille de la partition ESP pour GRUB2 : 600 Mo
efiSystemPartitionSize: 600M

essentialMounts: [ "live-*", "control", "ventoy" ]

lvm:
    enable: false
