# Configuration du module shellprocess-postinstall pour Arrera Linux
# Définit graphical.target comme cible de démarrage par défaut sur le système installé
---
dontChroot: false
timeout: 60

script:
    - command: "systemctl set-default graphical.target"
      timeout: 60
