# Configuration du module unpackfs pour Arrera Linux
# Copie du système racine LiveOS vers la partition cible
# Dans Fedora LiveOS, la racine décompressée est montée sur /run/rootfsbase
---
unpack:
    -   source: "/run/rootfsbase"
        sourcefs: "ext4"
        destination: ""
