# Configuration du module unpackfs pour Arrera Linux
# Décompression de l'image racine squashfs Fedora LiveOS
---
unpack:
    -   source: "/run/initramfs/live/LiveOS/squashfs.img"
        sourcefs: "squashfs"
        destination: ""
    -   source: "/run/install/repo/LiveOS/squashfs.img"
        sourcefs: "squashfs"
        destination: ""
    -   source: "/run/initramfs/live/LiveOS/rootfs.img"
        sourcefs: "ext4"
        destination: ""
    -   source: "/dev/mapper/live-base"
        sourcefs: "ext4"
        destination: ""
