# Configuration du module users pour Arrera Blue Édition Home
# Gestion des utilisateurs et privilèges d'administration
---
defaultGroups:
    - wheel
    - users
    - audio
    - video
    - dialout
    - storage
    - optical
    - network
    - input

autologinGroup: wheel
sudoersGroup: wheel
setRootPassword: false
doAutologin: false
allowWeakPasswords: false
user_shell: /bin/bash
avatarInstall: true

# Nom de machine fixe par défaut
hostname: "arrera"
