# Configuration du module users pour Arrera Blue Édition Éducation
# Compte prédéfini "parents" et nom de machine "arrera-school"
---
defaultGroups:
    - wheel
    - users
    - audio
    - video
    - dialout
    - storage
    - optical
    - network
    - input

autologinGroup: wheel
sudoersGroup: wheel
setRootPassword: false
doAutologin: false
allowWeakPasswords: false
user_shell: /bin/bash
avatarInstall: true

# Compte utilisateur prédéfini pour l'environnement scolaire / familial
fullName: "Parents"
loginName: "parents"

# Nom de machine fixe par défaut
hostname: "arrera-school"
