# Configuration du module users pour Arrera Linux
# Gestion des utilisateurs et privilèges d'administration (groupe wheel)
---
defaultGroups:
    - wheel
    - users
    - audio
    - video
    - dialout
    - storage
    - optical
    - network
    - input

autologinGroup: wheel
sudoersGroup: wheel
setRootPassword: false
doAutologin: false
allowWeakPasswords: false
user_shell: /bin/bash
avatarInstall: true
