# Configuration du module users pour Arrera Blue Édition Serveur
# Saisie complète utilisateur + saisie obligatoire du mot de passe root
---
defaultGroups:
    - wheel
    - users
    - audio
    - video
    - dialout
    - storage
    - optical
    - network
    - input

autologinGroup: wheel
sudoersGroup: wheel

# Activation explicite de la saisie du mot de passe administrateur (root)
setRootPassword: true
doReusePassword: false

doAutologin: false
allowWeakPasswords: false
user_shell: /bin/bash
avatarInstall: true
