# Configuration du module d'accueil (welcome) pour Arrera Linux
# Vérifications des prérequis système (Internet facultatif)
---
showSupportUrl: false
showKnownIssuesUrl: false
showReleaseNotesUrl: false
showDonateUrl: false

requirements:
    requiredStorage: 15.0
    requiredRam: 2.0
    internetCheckUrl: "https://fedoraproject.org"
    check:
        - storage
        - ram
        - power
        - internet
    required:
        - storage
        - ram
