# Configuration du module d'accueil (welcome) pour Arrera Blue 2026
# Vérifications des prérequis système
---
showSupportUrl: false
showKnownIssuesUrl: false
showReleaseNotesUrl: false
showDonateUrl: false

requirements:
    requiredStorage: 10.0
    requiredRam: 1.5
    internetCheckUrl: "https://fedoraproject.org"
    check:
        - storage
        - ram
        - power
        - internet
    required:
        - ram
